### ISSUE TITLE
REST API client seems buggy

### ISSUE THREAD

**Issue by W1zardsCh3ss** [massive-com/client-python#748]
**Describe the bug**

I've followed your docs and they appear to be misleading. I installed your client, but it states that it cannot find RESTClient when I run the program.

**To Reproduce**

Just follow your documentation and try to do any basic command... 

**Expected behavior**

The program should just run...

**Screenshots**

code pasted below

**Additional context**

(.venv) ╭─lux@Luminosity ~/Documents/Projects/Python/Tomic_root ‹main●› 
╰─$ /Users/lux/Documents/Projects/Python/Tomic_root/.venv/bin/python3 /Users/lux/Documents/Projects/Python/Tomic_root/Tomic/polygon_client.py
Traceback (most recent call last):
  File "/Users/lux/Documents/Projects/Python/Tomic_root/Tomic/polygon_client.py", line 8, in <module>
    from polygon import RESTClient
ImportError: cannot import name 'RESTClient' from 'polygon' (unknown location)

**Comment by justinpolygon** [comment]
Hi @W1zardsCh3ss, have you run `pip install -U polygon-api-client`? What does `pip list` say?

**Comment by justinpolygon** [comment]
Very strange. Can you maybe try reinstalled via:

```
pip uninstall polygon-api-client
pip install -U polygon-api-client
```

Also, do you mind posting the script you're using so I can try and reproduce? I don't think I've seen this before `Required-by: tomic` how are you installing the client?

**Comment by justinpolygon** [comment]
Yeah, I'm not sure either. Happy it worked thought.
