### ISSUE TITLE
cannot import name 'WebSocketClient' from partially initialized module 'polygon

### ISSUE THREAD

**Issue by hhashim1** [massive-com/client-python#88]
I am unable to launch the websocket example file. I have installed the polygon-api-client API however I am still getting the below error. Can someone please help me figure out what I am missing or doing wrong? Thank you!

`
  Message=cannot import name 'WebSocketClient' from partially initialized module 'polygon' (most likely due to a circular import) (e:\Dropbox\Documents\Visual Studio 2019\repos\polygon-client-python\websocket_example\polygon.py)
  Source=E:\Dropbox\Documents\Visual Studio 2019\repos\polygon-client-python\websocket_example\polygon.py
  StackTrace:
  File "E:\Dropbox\Documents\Visual Studio 2019\repos\polygon-client-python\websocket_example\polygon.py", line 5, in <module> (Current frame)
    from polygon import WebSocketClient, STOCKS_CLUSTER
  File "E:\Dropbox\Documents\Visual Studio 2019\repos\polygon-client-python\websocket_example\polygon.py", line 5, in <module>
    from polygon import WebSocketClient, STOCKS_CLUSTER

`

**Comment by ahmedminhaj6174** [comment]
import time
import ast
import sqlite3
import pandas as pd
from typing import List
from polygon import WebSocketClient, STOCKS_CLUSTER, CRYPTO_CLUSTER, FOREX_CLUSTER

ImportError: cannot import name 'STOCKS_CLUSTER' from 'polygon' (/Users/minhaj/opt/anaconda3/lib/python3.9/site-packages/polygon/__init__.py)


how to resolve this issue?
